### PR TITLE
feat: Add RPC sendDeviceInfo() + device-info event

### PR DESCRIPTION
**Pull request by gmaclennan**
First part of #245

TODO: tests

### CODE REVIEW

**Comment by achou11** [comment]
@gmaclennan is this ready for review?

**Comment by gmaclennan** [comment]
No tests yet, but otherwise done.

**Review by achou11 — COMMENTED** [review]
changes lgtm so far! can re-review when tests are added

**Comment by achou11** [comment]
@gmaclennan added a couple of tests in https://github.com/digidem/mapeo-core-next/pull/270/commits/8fdb7ea2adf7b87e79541803d229f5ddea31e569 if you want to take a second to look through those before merging

**Comment by gmaclennan** [comment]
Looks good to me. I can't approve since I own the PR, but ok to merge.

**Pull request merged**
