### PR TITLE
feat: update main exports

### PR DESCRIPTION
**Pull request by achou11**
Towards #278 

Waiting for #283 to be merged since it also includes some relevant changes

Summary of changes (so far):

- [X] adds `MapeoManager` to exports
- [X] removes `MapeoProjects` from exports

### CODE REVIEW

**Comment by achou11** [comment]
@gmaclennan anything else that you think should be updated in this PR?

**Comment by gmaclennan** [comment]
> @gmaclennan anything else that you think should be updated in this PR?

I don't think so. I already did all the work for publishing typescript types, and have done a test publish as a module. It is currently published as `@mapeo/core@9.0.0-alpha.0`, and only the `alpha` npm dist tag points to it - the `latest` dist tag points to v8.6.2 (we should keep it like that for now).  To install do `npm i @mapeo/core@alpha` or use the specific version `npm i @mapeo/core@9.0.0-alpha.0`

**Comment by gmaclennan** [comment]
Maybe remove the MapeoProject export now? Not sure it is needed?

**Comment by achou11** [comment]
> Maybe remove the MapeoProject export now? Not sure it is needed?

Feel like it'd be useful to keep if we're talking about general usage of this library, but if we're not concerned about that right now then that's okay too

**Review by gmaclennan — APPROVED** [review]

**Pull request merged**
