### PR TITLE
feat: Add SyncController [2/2]

### PR DESCRIPTION
**Pull request by gmaclennan**
The sync controller implements the `replicate()` method, manages sync state, and peer sync controller instances.

This PR is missing tests, but given the complexity of setting up unit tests to invite peers and add data, I think the time is better spent actually implementing and integrating that on the API, so that we can go straight to an e2e test.

### CODE REVIEW

**Review by achou11 — APPROVED** [review]
Will stopping/disabling sync be a follow-up?

**Comment by gmaclennan** [comment]
Yes good point it should be yes

**Comment by achou11** [comment]
did you mean to merge instead of close?

**Comment by gmaclennan** [comment]
> did you mean to merge instead of close?

No, deleting the base branch automatically closed this (I merged the peer sync controller PR first, which maybe I shouldn't have done - I still haven't figured out the best flow for stacked PRs)

**Pull request merged**
